CREATE TABLE CHARACTERS_SERIES(
	id INT PRIMARY KEY,
	id_serie INT,
	id_character INT
);

INSERT INTO CHARACTERS_SERIES VALUES (1, 1, 2);
INSERT INTO CHARACTERS_SERIES VALUES (2, 1, 4);
INSERT INTO CHARACTERS_SERIES VALUES (3, 1, 1);
INSERT INTO CHARACTERS_SERIES VALUES (4, 2, 1);
INSERT INTO CHARACTERS_SERIES VALUES (5, 3, 4);
INSERT INTO CHARACTERS_SERIES VALUES (6, 3, 5);
INSERT INTO CHARACTERS_SERIES VALUES (7, 4, 6);
INSERT INTO CHARACTERS_SERIES VALUES (8, 5, 7);
INSERT INTO CHARACTERS_SERIES VALUES (9, 5, 8);
INSERT INTO CHARACTERS_SERIES VALUES (10, 5, 9);
INSERT INTO CHARACTERS_SERIES VALUES (11, 5, 10);
